<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tindakan_model extends CI_Model
{

    public $table = 'tindakan';
    public $id = 'id_tindakan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_tindakan,status,keluhan,id_dokter,nama_dokter,id_pasien,nama_pasien,tgl_tindakan,id_jenis_tindakan,jenis_tindakan,penyakit,resep');
        $this->datatables->from('tindakan');
        //add this line for join
        $this->datatables->join('penyakit', 'tindakan.id_penyakit  = penyakit.id_penyakit ');
        $this->datatables->add_column('action', anchor(site_url('tindakan/read/$1'),'Read')." | ".anchor(site_url('tindakan/update/$1'),'Update')." | ".anchor(site_url('tindakan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_tindakan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    
    // get data by id
    function get_by_id($id)
    {   $this->db->join('penyakit', 'tindakan.id_penyakit  = penyakit.id_penyakit ');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_tindakan', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('keluhan', $q);
	$this->db->or_like('id_dokter', $q);
	$this->db->or_like('nama_dokter', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('nama_pasien', $q);
	$this->db->or_like('tgl_tindakan', $q);
	$this->db->or_like('id_jenis_tindakan', $q);
	$this->db->or_like('jenis_tindakan', $q);
	$this->db->or_like('id_penyakit', $q);
	$this->db->or_like('resep', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tindakan', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('keluhan', $q);
	$this->db->or_like('id_dokter', $q);
	$this->db->or_like('nama_dokter', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('nama_pasien', $q);
	$this->db->or_like('tgl_tindakan', $q);
	$this->db->or_like('id_jenis_tindakan', $q);
	$this->db->or_like('jenis_tindakan', $q);
	$this->db->or_like('id_penyakit', $q);
	$this->db->or_like('resep', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tindakan_model.php */
/* Location: ./application/models/Tindakan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-23 18:29:47 */
/* http://harviacode.com */